apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: talend
  namespace: a-main
spec:
  selector:
    app: talend
  replicas: 0
  template:
    metadata:
      labels:
        app: talend
    spec:
      triggers:
        image.openshift.io/triggers: |-
          [
            {
              "from": {
                "kind": "ImageStreamTag",
                "name": "talend:latest"
              },
              "fieldPath": "spec.template.spec.containers[0].image"
            }
          ]
      containers:
        - name: talend
          image: image-registry.openshift-image-registry.svc:5000/a-main/talend:latest
          ports:
            - containerPort: 8080

###
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: talend
  namespace: a-main
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/ShaktiAhad/AWS.git'
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'talend:latest'

###
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: talend
  namespace: a-main
