apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    description: Defines how to deploy the application server
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{"description":"Defines
      how to deploy the application server","template.alpha.openshift.io/wait-for-ready":"true"},"creationTimestamp":"2021-05-07T06:12:51Z","generation":480,"labels":{"app":"ccifacommission-calc-web","scaled-down-by-jenkins":"true","template":"nodejs-app"},"managedFields":[{"apiVersion":"apps.openshift.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:description":{},"f:template.alpha.openshift.io/wait-for-ready":{}},"f:labels":{".":{},"f:app":{},"f:template":{}}},"f:spec":{"f:selector":{".":{},"f:name":{}},"f:strategy":{"f:activeDeadlineSeconds":{},"f:rollingParams":{".":{},"f:intervalSeconds":{},"f:maxSurge":{},"f:maxUnavailable":{},"f:timeoutSeconds":{},"f:updatePeriodSeconds":{}},"f:type":{}},"f:template":{".":{},"f:metadata":{".":{},"f:creationTimestamp":{},"f:labels":{".":{},"f:name":{}},"f:name":{}},"f:spec":{".":{},"f:containers":{".":{},"k:{\"name\":\"ccifacommission-calc-web\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"NPM_RUN\"}":{".":{},"f:name":{},"f:value":{}}},"f:imagePullPolicy":{},"f:livenessProbe":{".":{},"f:failureThreshold":{},"f:httpGet":{".":{},"f:port":{},"f:scheme":{}},"f:initialDelaySeconds":{},"f:periodSeconds":{},"f:successThreshold":{},"f:timeoutSeconds":{}},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":4000,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:protocol":{}}},"f:readinessProbe":{".":{},"f:failureThreshold":{},"f:httpGet":{".":{},"f:port":{},"f:scheme":{}},"f:initialDelaySeconds":{},"f:periodSeconds":{},"f:successThreshold":{},"f:timeoutSeconds":{}},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{}},"f:requests":{".":{},"f:cpu":{}}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}},"f:triggers":{}}},"manager":"oc","operation":"Update","time":"2021-06-03T23:01:39Z"},{"apiVersion":"apps.openshift.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:template":{"f:spec":{"f:containers":{"k:{\"name\":\"ccifacommission-calc-web\"}":{"f:env":{"k:{\"name\":\"API_HOST\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"APP_HOST\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"APP_PORT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"DATE_PARAMETER_ALLOWED\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"LOG_LEVEL\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"MANAGER_JOB_CODES\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"REACT_APP_DATE_PARAMETER_ALLOWED\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"REACT_APP_SHOW_LOGOUT_BUTTON\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"SALES_MANAGER_JOB_CODES\"}":{".":{},"f:name":{},"f:value":{}}},"f:livenessProbe":{"f:httpGet":{"f:path":{}}},"f:readinessProbe":{"f:httpGet":{"f:path":{}}},"f:resources":{"f:limits":{"f:memory":{}},"f:requests":{"f:memory":{}}}}}}}}},"manager":"Mozilla","operation":"Update","time":"2021-11-25T04:57:58Z"},{"apiVersion":"apps.openshift.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:availableReplicas":{},"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:details":{".":{},"f:causes":{},"f:message":{}},"f:latestVersion":{},"f:observedGeneration":{},"f:readyReplicas":{},"f:replicas":{},"f:unavailableReplicas":{},"f:updatedReplicas":{}}},"manager":"openshift-controller-manager","operation":"Update","time":"2021-12-10T07:10:29Z"},{"apiVersion":"apps.openshift.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{"f:scaled-down-by-jenkins":{}}},"f:spec":{"f:replicas":{},"f:template":{"f:spec":{"f:containers":{"k:{\"name\":\"ccifacommission-calc-web\"}":{"f:image":{}}}}}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2021-12-10T11:31:13Z"}],"name":"ccifacommission-calc-web","namespace":"ccifacommission-dev-axa-li-jp","resourceVersion":"1864341627","uid":"a0b4a359-7cf0-412f-882e-38c923ad9169"},"spec":{"replicas":0,"revisionHistoryLimit":10,"selector":{"name":"ccifacommission-calc-web"},"strategy":{"activeDeadlineSeconds":21600,"resources":{},"rollingParams":{"intervalSeconds":1,"maxSurge":"25%","maxUnavailable":"25%","timeoutSeconds":600,"updatePeriodSeconds":1},"type":"Rolling"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"ccifacommission-calc-web"},"name":"ccifacommission-calc-web"},"spec":{"containers":[{"env":[{"name":"NPM_RUN","value":"start"},{"name":"APP_HOST","value":"https://ccifacommission-calc-web-dev.axa-li-jp-dev-int.scarlet.ap-southeast-1.aws.openpaas.axa-cloud.com"},{"name":"APP_PORT","value":"4000"},{"name":"API_HOST","value":"https://ccifacommission-calc-api-dev.axa-li-jp-dev-int.scarlet.ap-southeast-1.aws.openpaas.axa-cloud.com"},{"name":"DATE_PARAMETER_ALLOWED","value":"1"},{"name":"REACT_APP_DATE_PARAMETER_ALLOWED","value":"1"},{"name":"LOG_LEVEL","value":"debug"},{"name":"SALES_MANAGER_JOB_CODES","value":"ABA1,ABAM,ABB1"},{"name":"MANAGER_JOB_CODES","value":"S4C,S3C"},{"name":"REACT_APP_SHOW_LOGOUT_BUTTON","value":"0"}],"image":"image-registry.openshift-image-registry.svc:5000/ccifacommission-dev-axa-li-jp/ccifacommission-calc-web:0.0.0","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/api/up","port":4000,"scheme":"HTTP"},"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":3},"name":"ccifacommission-calc-web","ports":[{"containerPort":4000,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/api/up","port":4000,"scheme":"HTTP"},"initialDelaySeconds":3,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":3},"resources":{"limits":{"cpu":"400m","memory":"600Mi"},"requests":{"cpu":"400m","memory":"600Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}},"test":false,"triggers":[]},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-12-09T23:47:10Z","lastUpdateTime":"2021-12-09T23:47:10Z","message":"Deployment
      config has minimum availability.","status":"True","type":"Available"},{"lastTransitionTime":"2021-12-10T07:10:48Z","lastUpdateTime":"2021-12-10T07:10:51Z","message":"replication
      controller \"ccifacommission-calc-web-140\" successfully rolled out","reason":"NewReplicationControllerAvailable","status":"True","type":"Progressing"}],"details":{"causes":[{"type":"Manual"}],"message":"manual
      change"},"latestVersion":140,"observedGeneration":480,"readyReplicas":1,"replicas":1,"unavailableReplicas":0,"updatedReplicas":1}}

      '
    template.alpha.openshift.io/wait-for-ready: 'true'
  labels:
    app: ccifacommission-calc-web
    scaled-down-by-jenkins: 'true'
    template: nodejs-app
  name: ccifacommission-calc-web
  namespace: ccifacommission-dev-axa-li-jp
spec:
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    name: ccifacommission-calc-web
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ccifacommission-calc-web
      name: ccifacommission-calc-web
    spec:
      containers:
      - env:
        - name: NPM_RUN
          value: start
        - name: APP_HOST
          value: https://ccifacommission-calc-web-dev.axa-li-jp-dev-int.scarlet.ap-southeast-1.aws.openpaas.axa-cloud.com
        - name: APP_PORT
          value: '4000'
        - name: API_HOST
          value: https://ccifacommission-calc-api-dev.axa-li-jp-dev-int.scarlet.ap-southeast-1.aws.openpaas.axa-cloud.com
        - name: DATE_PARAMETER_ALLOWED
          value: '1'
        - name: REACT_APP_DATE_PARAMETER_ALLOWED
          value: '1'
        - name: LOG_LEVEL
          value: debug
        - name: SALES_MANAGER_JOB_CODES
          value: ABA1,ABAM,ABB1
        - name: MANAGER_JOB_CODES
          value: S4C,S3C
        - name: REACT_APP_SHOW_LOGOUT_BUTTON
          value: '0'
        image: image-registry.openshift-image-registry.svc:5000/ccifacommission-dev-axa-li-jp/ccifacommission-calc-web:0.0.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/up
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: ccifacommission-calc-web
        ports:
        - containerPort: 4000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/up
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 400m
            memory: 600Mi
          requests:
            cpu: 400m
            memory: 600Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers: []
