apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"image.openshift.io/v1","kind":"ImageStream","metadata":{"annotations":{},"labels":{"app":"ccifacommission-calc-api","template":"java-app"},"name":"ccifacommission-calc-api","namespace":"ccifacommission-dev-axa-li-jp"}}

      '
  labels:
    app: ccifacommission-calc-api
    template: java-app
  name: ccifacommission-calc-api
  namespace: ccifacommission-dev-axa-li-jp
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: ccifacommission-calc-api@sha256:b8768d4a3dd1dc819b8d5f79a54253bf9627f3dc4aa7b04d2c442ca153ddf181
      namespace: ccifacommission-dev-axa-li-jp
    generation: 26
    importPolicy: {}
    name: 0.0.1-SNAPSHOT
    referencePolicy:
      type: Source
